- mode : image
  images_path: ../data/imgs_MOV03478
  groundtruth_path: ../layout/mov03478.csv
  model_name: lite_mobilenet_v2
  adapter_name: AdapterDetectionTask
  path_classes : ../modeles/lite_mobilenet_v2/coco_91cl_bkgr.txt
  path_weights : ../modeles/lite_mobilenet_v2/frozen_inference_graph.pb
  path_config : ../modeles/lite_mobilenet_v2/lite_mobilenet_v2.pbtxt
  confidence: 0.1
  nms_threshold: 0.4
  scale: 1.0
  size: 300 300
  mean: 0 0 0
  swapRB: True