- mode : image
  images_path: ./data/imgs_MOV03478
  groundtruth_path: ./layout/mov03478.csv
  model_name: FasterRCNN
  adapter_name: AdapterFasterRCNN
  path_classes: ./models/FasterRCNN/FasterRCNN_COCO_V1_classes.txt
  write_path: ./data/FasterRCNN_test_out.csv     # personalize
  confidence: 0.5
  nms_threshold: 0.4
  scale: 1.0      # placeholder
  size: 312 312   # placeholder
  mean:           # placeholder
  swapRB:         # placeholder